# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: [16.x]

      - name: Install Dependencies
        run: npm install --dev

      - name: Run Linting
        run: npx eslint .
        env:
          CI: true

      - name: Build React App
        run: npm run build

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Python Build Cache
        cache: 'pip'

        run: pip install -r requirements.txt
        with:
          path: 'requirements.txt'

        run: python main.py
